# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Dcouple.Everyport
PackageVersion: "0.1.2"
InstallerType: wix
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/greenfield-inc/everyport/releases/download/v0.1.2/everyport-0.1.2-x86_64.msi
    InstallerSha256: "298610f29cefb8a415364dad951099d28462cf46956fd89388a799ca9cf11fbd"
ManifestType: installer
ManifestVersion: 1.12.0
